name: Deploy buy runner

on:
  push:
    branches: ["main", "dev"]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Stop and remove containers, networks
        env:
          # EXPOSE_PORT: ${{ secrets.EXPOSE_PORT }}
          EXPOSE_PORT: 3004
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        env:
          # EXPOSE_PORT: ${{ secrets.EXPOSE_PORT }}
          EXPOSE_PORT: 3004
        run: docker-compose up -d
